services:
  mysql:
    image: mysql:8.0
    container_name: security-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: security_db
      MYSQL_USER: security_user
      MYSQL_PASSWORD: ek
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: